window.CORE_DRIFT_ASSETS = {
  crates: {
    basic: "assets/crates/crate-basic.png",
    bronze: "assets/crates/crate-bronze.png",
    metal: "assets/crates/crate-metal.png",
    gold: "assets/crates/crate-gold.png",
    royal: "assets/crates/crate-royal.png",
  },
  legacyCharacters: {
    player: "assets/characters/new-piskel.png",
    moveLeft: "assets/characters/move-left.png",
    moveRight: "assets/characters/move-right.png",
  },
  items: {
    magicStaffPickup: "assets/items/magic-staff-pickup.png?v=20260610-1",
  },
  vfx: {
    glockMuzzleFlash: "assets/vfx/glock-muzzle-flash.png",
    dashDust: "assets/vfx/dash-dust.png",
    walkingDust: "assets/vfx/walking-dust-directional-mid-01.png",
    bloodDrops: "assets/vfx/blood-drops-01.png",
    bazookaExplosionFire02: "assets/vfx/bazooka-explosion-fire-02.png",
    poisonProjectileUnityCaptureSheet: "assets/vfx/poison-projectile-unity-capture-sheet.png?v=20260609-1",
    poisonProjectileUnityCapture: "assets/vfx/poison-projectile-unity-capture.png?v=20260608-1",
    poisonProjectile: "assets/vfx/poison-projectile-blur-circle.png",
    poisonProjectileSplash04: "assets/vfx/poison-projectile-splash04.png",
    poisonProjectileSplash07: "assets/vfx/poison-projectile-splash07.png",
    poisonProjectileSplash02Blur: "assets/vfx/poison-projectile-splash02-blur.png",
  },
  skillVfx: {
    teleport: "assets/vfx/skills/teleport.png",
    vanish: "assets/vfx/skills/vanish.png",
    bloodCloud: "assets/vfx/skills/blood-cloud-01.png?v=20260601-1",
    staticCollapseCharge: "assets/vfx/skills/static-collapse-lightning-07.png",
    staticCollapseBurst: "assets/vfx/skills/static-collapse-lightning-08.png",
    lightningThrustAura: "assets/vfx/skills/lightning-thrust-04.png",
    lightningThrustScatter06: "assets/vfx/skills/lightning-thrust-06.png",
    lightningThrustScatter08: "assets/vfx/skills/static-collapse-lightning-08.png",
    toxicOrb: "assets/vfx/skills/toxic-orb-01-capture-sheet.png?v=20260609-1",
    lightning: "assets/vfx/skills/lightning.png",
    magicImpact: "assets/vfx/skills/magic-impact.png",
    lightningImpact: "assets/vfx/skills/lightning-impact.png",
    burstImpact: "assets/vfx/skills/burst-impact.png",
    swordSlash: "assets/vfx/skills/sword-slash.png",
    poisonSlash: "assets/vfx/skills/slash-poison-01.png",
    impactSparks: "assets/vfx/skills/impact-sparks.png",
    wizardBossSpawnPoisonExplosion02: "assets/vfx/skills/wizard-boss-spawn-poison-explosion-02.png",
    // Previous wizard spawn VFX kept for rollback:
    // wizardBossSpawnFireBurstSmokeBig01: "assets/vfx/wizard-boss-spawn-smoke.png?v=20260605-2",
  },
  audio: {
    glockShot: "assets/sounds/glock-shot.mp3",
    glockReload: "assets/sounds/glock-reload.mp3",
    awmShot: "assets/sounds/awm-shot.mp3",
    awmReload: "assets/sounds/awm-reload.mp3",
    knifeSwing: "assets/sounds/knife-swing.mp3",
    knifeThrow: "assets/sounds/knife-throw.mp3",
    lightningThrust: "assets/sounds/lightning-thrust.wav",
  },
};
