window.CORE_DRIFT_SKILLS = {
  knifeRecall: {
    label: "Knife Teleport",
    cooldown: 5,
    icon: "skill-icon-knife-recall",
    requiresKnife: true,
  },
  lightningThrust: {
    label: "Lightning Thrust",
    cooldown: 8,
    range: 360,
    damage: 85,
    hitRadius: 42,
    icon: "skill-icon-lightning-thrust",
    requiresKnife: true,
  },
  railburst: {
    label: "Railburst",
    cooldown: 10,
    chargeSeconds: 0.45,
    range: 1500,
    width: 160,
    damage: 150,
    icon: "skill-icon-railburst",
  },
  staticCollapse: {
    label: "Static Collapse",
    cooldown: 12,
    delay: 0.8,
    radius: 260,
    damage: 90,
    projectileSpeed: 760,
    contactDamage: 36,
    chargeMax: 1.4,
    minRange: 280,
    maxRange: 1240,
    icon: "skill-icon-static-collapse",
  },
  arcPrison: {
    label: "Arc Prison",
    cooldown: 16,
    radius: 240,
    damage: 45,
    edgeWidth: 7,
    slowSeconds: 1.6,
    icon: "skill-icon-arc-prison",
  },
  stormRecall: {
    label: "Storm Recall",
    cooldown: 18,
    radius: 200,
    damage: 40,
    icon: "skill-icon-storm-recall",
  },
};
