window.CORE_DRIFT_WEAPONS = {
  selectedSlot: 1,
  slots: {
    1: "knife",
    2: null,
    3: null,
  },
  knife: {
    damage: 25,
    fireRate: 1,
    range: 82,
    throwLifeBonus: 0,
    throwSpeedBonus: 0,
    arc: Math.PI * 0.72,
    swingDuration: 0.18,
    count: 1,
    upgrades: { range: 0, damage: 0, mag: 0, speed: 0 },
  },
  fist: {
    damage: 10,
    fireRate: 0.36,
    range: 52,
    arc: Math.PI * 0.62,
    swingDuration: 0.16,
  },
  glock: {
    damage: 50,
    bulletSpeed: 880,
    fireRate: 0.9,
    bulletRadius: 7,
    bulletLife: 1.2,
    ammo: 0,
    magAmmo: 0,
    magazineSize: 17,
    reloadTime: 3,
    reloadTimer: 0,
    upgrades: { range: 0, damage: 0, mag: 0, speed: 0 },
  },
  awm: {
    damage: 100,
    bulletSpeed: 1500,
    fireRate: 0.85,
    bulletRadius: 5,
    bulletLife: 4,
    ammo: 0,
    magAmmo: 0,
    magazineSize: 6,
    reloadTime: 5,
    reloadTimer: 0,
    upgrades: { range: 0, damage: 0, mag: 0, speed: 0 },
  },
  bazooka: {
    damage: 170,
    bulletSpeed: 540,
    fireRate: 0.7,
    bulletRadius: 11,
    bulletLife: 3.2,
    ammo: 0,
    magAmmo: 0,
    magazineSize: 1,
    reloadTime: 4,
    reloadTimer: 0,
    explosionRadius: 156,
    upgrades: { range: 0, damage: 0, mag: 0, speed: 0 },
  },
  grenade: {
    damage: 125,
    bulletSpeed: 470,
    fireRate: 0.46,
    bulletRadius: 12,
    bulletLife: 4,
    count: 0,
    ammo: 0,
    magAmmo: 0,
    magazineSize: 1,
    reloadTime: 1.1,
    reloadTimer: 0,
    explosionRadius: 132,
    upgrades: { range: 0, damage: 0, mag: 0, speed: 0 },
  },
  magicStaff: {
    count: 0,
    fireRate: 0.55,
    castDuration: 0.42,
    slashDamage: 58,
    slashRange: 128,
    slashArc: Math.PI * 0.9,
    slashSize: 260,
    projectileDamage: 30,
    projectileSpeed: 660,
    projectileRadius: 13,
    projectileLife: 4.55,
    projectileTurnRate: 7.8,
    upgrades: { range: 0, damage: 0, mag: 0, speed: 0 },
  },
};
